In [2]:
import pandas as pd
df = pd.read_csv('../data/interim/cleaned_matches.csv')
df.head()

,match_id,date,competition,season,home_team,away_team,home_goals,away_goals,result,venue,neutral
0,1,1872-11-30,Friendly,1872,Scotland,England,0.0,0.0,D,Glasgow,False
1,2,1873-03-08,Friendly,1873,England,Scotland,4.0,2.0,H,London,False
2,3,1874-03-07,Friendly,1874,Scotland,England,2.0,1.0,H,Glasgow,False
3,4,1875-03-06,Friendly,1875,England,Scotland,2.0,2.0,D,London,False
4,5,1876-03-04,Friendly,1876,Scotland,England,3.0,0.0,H,Glasgow,False

In [1]:
import pandas as pd
teams = pd.read_csv(
    "../data/raw/teams/teams.csv"
)
print(teams.shape)
print(teams.columns.tolist())
teams.head()

(48, 136)
['team', 'team_country', 'players_used', 'avg_age', 'possession', 'games', 'games_starts', 'minutes', 'minutes_90s', 'goals', 'assists', 'goals_assists', 'goals_pens', 'pens_made', 'pens_att', 'cards_yellow', 'cards_red', 'goals_per90', 'assists_per90', 'goals_assists_per90', 'goals_pens_per90', 'goals_assists_pens_per90', 'players_used_against', 'avg_age_against', 'possession_against', 'games_against', 'games_starts_against', 'minutes_against', 'minutes_90s_against', 'goals_against', 'assists_against', 'goals_assists_against', 'goals_pens_against', 'pens_made_against', 'pens_att_against', 'cards_yellow_against', 'cards_red_against', 'goals_per90_against', 'assists_per90_against', 'goals_assists_per90_against', 'goals_pens_per90_against', 'goals_assists_pens_per90_against', 'shots', 'shots_on_target', 'shots_on_target_pct', 'shots_per90', 'shots_on_target_per90', 'goals_per_shot', 'goals_per_shot_on_target', 'shots_against', 'shots_on_target_against', 'shots_on_target_pct_against', 'shots_per90_against', 'shots_on_target_per90_against', 'goals_per_shot_against', 'goals_per_shot_on_target_against', 'minutes_per_game', 'minutes_pct', 'minutes_per_start', 'games_complete', 'games_subs', 'minutes_per_sub', 'unused_subs', 'points_per_game', 'on_goals_for', 'on_goals_against', 'plus_minus', 'plus_minus_per90', 'minutes_per_game_against', 'minutes_pct_against', 'minutes_per_start_against', 'games_complete_against', 'games_subs_against', 'minutes_per_sub_against', 'unused_subs_against', 'points_per_game_against', 'on_goals_for_against', 'on_goals_against_against', 'plus_minus_against', 'plus_minus_per90_against', 'cards_yellow_red', 'fouls', 'fouled', 'offsides', 'crosses', 'interceptions', 'tackles_won', 'pens_won', 'pens_conceded', 'own_goals', 'cards_yellow_red_against', 'fouls_against', 'fouled_against', 'offsides_against', 'crosses_against', 'interceptions_against', 'tackles_won_against', 'pens_won_against', 'pens_conceded_against', 'own_goals_against', 'gk_games', 'gk_games_starts', 'gk_minutes', 'gk_goals_against', 'gk_goals_against_per90', 'gk_shots_on_target_against', 'gk_saves', 'gk_save_pct', 'gk_wins', 'gk_ties', 'gk_losses', 'gk_clean_sheets', 'gk_clean_sheets_pct', 'gk_pens_att', 'gk_pens_allowed', 'gk_pens_saved', 'gk_pens_missed', 'gk_pens_save_pct', 'gk_games_against', 'gk_games_starts_against', 'gk_minutes_against', 'gk_goals_against_against', 'gk_goals_against_per90_against', 'gk_shots_on_target_against_against', 'gk_saves_against', 'gk_save_pct_against', 'gk_wins_against', 'gk_ties_against', 'gk_losses_against', 'gk_clean_sheets_against', 'gk_clean_sheets_pct_against', 'gk_pens_att_against', 'gk_pens_allowed_against', 'gk_pens_saved_against', 'gk_pens_missed_against', 'gk_pens_save_pct_against']

,team,team_country,players_used,avg_age,possession,games,games_starts,minutes,minutes_90s,goals,...,gk_wins_against,gk_ties_against,gk_losses_against,gk_clean_sheets_against,gk_clean_sheets_pct_against,gk_pens_att_against,gk_pens_allowed_against,gk_pens_saved_against,gk_pens_missed_against,gk_pens_save_pct_against
0,Algeria,Algeria,22,27.7,63.0,3,33,270,3.0,5,...,1,1,1,1,33.3,0,0,0,0,NaN
1,Argentina,Argentina,24,29.7,58.3,3,33,270,3.0,8,...,0,0,3,0,0.0,2,1,0,1,0.0
2,Australia,Australia,20,25.6,40.7,3,33,270,3.0,2,...,1,1,1,2,66.7,0,0,0,0,NaN
3,Austria,Austria,20,29.3,48.0,3,33,270,3.0,5,...,1,1,1,1,33.3,1,1,0,0,0.0
4,Belgium,Belgium,20,29.8,57.8,4,44,390,4.3,8,...,0,2,2,1,25.0,1,1,0,0,0.0